### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by mysticmetal** [AbhirojPanwar/Wallser#1]
mine crashes at load

```
java.lang.ClassCastException: thenextvoyager.wallser.activity.MainActivity cannot be cast to thenextvoyager.wallser.callback.OnResultFetchedCallback
                                                                            at thenextvoyager.wallser.network.FetchImageVolley$1.onResponse(FetchImageVolley.java:51)
                                                                            at thenextvoyager.wallser.network.FetchImageVolley$1.onResponse(FetchImageVolley.java:48)
                                                                            at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:65)
                                                                            at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
```

**Comment by panwarab** [comment]
@mysticmetal  Yeah, The issue is because MainActivity does not implement the onResultFetchedCallback and yet we are trying to cast it's context to onResultFetchedCallback.

**Comment by mysticmetal** [comment]
sure. now that volley is deprecated can you use retrofit2 instead?
